#!/usr/bin/env bash

# Trap any program EXIT and run this function.
# Whether the deploy succeeds or fails, clean up the deploy branch.

function cleanup_at_exit {
  git checkout main

  git branch -D deploy
}
trap cleanup_at_exit EXIT

# checks out a new branch called "deploy". Note that the name "deploy" here isn't magical,
# but it needs to match the name of the branch we specify when we push to our heroku remote.
git checkout -b deploy

webpack


# "force" add the otherwise gitignored build files
git add -f public/bundle.js public/bundle.js.map

# create a commit, even if nothing changed
git commit --allow-empty -m 'Deploying'

# push your local "deploy" branch to the "master" branch on heroku
git push --force heroku deploy:main
